--update PREGUNTAS set CODAREA = (select CODAREA from AREAS where AREAS.CODCOMPETENCIA = PREGUNTAS.CODCOMPETENCIA);

--Actualizar las areas de las preguntas 
--(CUIDADO: Se debio usar la tabla COMPONENTES y no COMPETENCIAS)
update PREGUNTAS a
left join COMPETENCIAS b on
    a.CODCOMPETENCIA = b.CODCOMPETENCIA
set
    a.CODAREA = b.CODAREA

--Insertar en encabezados
INSERT INTO ENCABEZADOS (DESCRIPCION, CODPREGUNTA)
SELECT PREGUNTAS.ENCABEZADO, PREGUNTAS.CODPREGUNTA FROM PREGUNTAS;

--Actualizar los encabezados de las preguntas
update PREGUNTAS a
left join ENCABEZADOS b on
    a.CODPREGUNTA = b.CODPREGUNTA
set
    a.ID_ENCABEZADO = b.ID_ENCABEZADO


--Preguntas con encabezado inexistente
SELECT PREGUNTAS.*
FROM PREGUNTAS LEFT JOIN ENCABEZADOS ON ENCABEZADOS.ID_ENCABEZADO=PREGUNTAS.ID_ENCABEZADO
WHERE ENCABEZADOS.ID_ENCABEZADO IS NULL;


--NOTA: Estableces ID_ENCABEZADO como por defecto NULL en la tabla Preguntas
--Eliminar encabezados vacios
DELETE FROM `ENCABEZADOS` WHERE DESCRIPCION = '';


--Retos que todos no han terminado
SELECT * FROM `participantes` where CORRECTAS + INCORRECTAS < (SELECT RETOS_ANTIGUO.TOTAL_PREGUNTAS FROM RETOS_ANTIGUO WHERE RETOS_ANTIGUO.CODRETO = PARTICIPANTES.CODRETO);

--Retos que alguien no ha terminado (Retos para 'Responde' en la aplicacion)
SELECT * FROM `participantes` where CORRECTAS + INCORRECTAS < (SELECT RETOS_ANTIGUO.TOTAL_PREGUNTAS FROM RETOS_ANTIGUO WHERE RETOS_ANTIGUO.CODRETO = PARTICIPANTES.CODRETO) AND PARTICIPANTES.EMAIL = 'andreshg112@gmail.com';